name: Build Extension

env:
  BUILD_VERSION: "1.0.${{github.run_number}}"
  BUILD_INFORMATION: "1.0.${{github.run_number}}+Branch.${{github.ref_name}}.Sha.${{github.sha}}"

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        run: |
          npm install -g @vscode/vsce
          npm install
          npm version "${{env.BUILD_VERSION}}"

      - name: Create Packages
        run: vsce package

      - name: Upload Packages
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: data-scripter-*.vsix
